language: node_js
node_js: 6.1.0
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp
script:
- npm run build
after_success:
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    git config credential.helper "store --file=.git/credentials"
    echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    git config --global user.name "Grommet Community Bot"
    git config --global user.email "eric.soderberg@hpe.com"
    gulp release:stable
  fi
